# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestEcshoplogin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ecshoplogin(self):
    self.vars["name"] = "tester"
    print(str(self.vars["name"]))
    self.driver.get("http://192.168.154.130/ecshop/")
    self.driver.set_window_size(885, 697)
    self.driver.find_element(By.CSS_SELECTOR, "#ECS_MEMBERZONE > a:nth-child(2) > img").click()
    self.driver.find_element(By.NAME, "submit").click()
    assert self.driver.switch_to.alert.text == "- 用户名不能为空。\\n- 登录密码不能为空。\\n"
    self.driver.find_element(By.CSS_SELECTOR, "#ECS_MEMBERZONE > a:nth-child(2) > img").click()
    print(str(self.vars["userCenterTitle"]))
    assert self.driver.title == "self.vars['userCenterTitle']"
    self.driver.find_element(By.NAME, "username").send_keys("abc")
    self.driver.find_element(By.NAME, "password").send_keys("123456")
    self.driver.find_element(By.NAME, "submit").click()
    assert self.driver.title == "系统提示_ECSHOP演示站 - Powered by ECShop"
    time.sleep(5000)
    assert self.driver.title == "self.vars['userCenterTitle']"
    self.driver.find_element(By.NAME, "username").send_keys(self.vars["name"])
    self.driver.find_element(By.NAME, "password").send_keys("123456")
    self.driver.find_element(By.NAME, "submit").click()
    assert self.driver.title == "系统提示_ECSHOP演示站 - Powered by ECShop"
    self.driver.find_element(By.LINK_TEXT, "留言板").click()
    self.driver.find_element(By.NAME, "msg_title").send_keys("tester的第一条留言")
    self.driver.find_element(By.NAME, "msg_content").send_keys("tester的第一条留言")
    self.driver.find_element(By.CSS_SELECTOR, ".bnt_blue_1").click()
    self.driver.find_element(By.LINK_TEXT, "退出").click()
  
