# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestBaidu():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_baidu(self):
    self.driver.get("https://www.baidu.com")
    self.driver.set_window_size(885, 692)
    self.driver.find_element(By.ID, "kw").click()
    self.driver.find_element(By.ID, "kw").send_keys("selenium")
    self.driver.find_element(By.ID, "su").click()
    self.driver.close()

if __name__ == "__main__":
    pytest.main()