# Generated by Selenium IDE
import pytest

from selenium import webdriver
from selenium.webdriver.common.by import By


class TestEcshopsearch:
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ecshopsearch(self):
    self.driver.get("http://192.168.154.130/ecshop/")
    self.driver.set_window_size(885, 697)
    self.driver.find_element(By.NAME, "imageField").click()
    assert self.driver.switch_to.alert.text == "请输入搜索关键词！"
    self.driver.find_element(By.ID, "keyword").send_keys("a")
    self.driver.find_element(By.NAME, "imageField").click()
    value = self.driver.find_element(By.ID, "keyword").get_attribute("value")
    assert value == "a"
    assert self.driver.find_element(By.CSS_SELECTOR, "b").text == "4"
    assert self.driver.find_element(By.LINK_TEXT, "P806").text == "P806"
    assert self.driver.find_element(By.CSS_SELECTOR, ".goodsItem:nth-child(1) > .shop_s").text == "￥2000元"
    self.vars["p806jg1"] = self.driver.find_element(By.CSS_SELECTOR, ".goodsItem:nth-child(1) > .shop_s").text
    print(str(self.vars["p806jg1"]))
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".goodsItem:nth-child(1) .goodsimg")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".goodsItem:nth-child(1) .goodsimg").click()
    self.vars["p806jg2"] = self.driver.find_element(By.ID, "ECS_SHOPPRICE").text
    print(str(self.vars["p806jg2"]))
    assert self.driver.find_element(By.ID, "ECS_SHOPPRICE").text == "self.vars[\"p806jg1\"]"
    value = self.driver.find_element(By.ID, "number").get_attribute("value")
    assert value == "1"
    assert self.driver.find_element(By.ID, "spec_value_167").is_selected() is True
    assert self.driver.find_element(By.ID, "spec_value_168").is_selected() is False
    self.driver.find_element(By.LINK_TEXT, "留言板").click()
    assert self.driver.title == "留言板_ECSHOP演示站 - Powered by ECShop"
    assert self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td:nth-child(2)").text == "匿名用户"


if __name__ == "__main__":
    pytest.main()
